services:
  - type: web
    name: rangoon-veraion1.0.0.1
    env: node
    # Updated build command to use db:setup instead of db:migrate
    # This creates all tables from scratch using raw SQL
    buildCommand: yarn install && yarn run build && yarn run db:setup
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: ERPNEXT_BASE_URL
        sync: false
      - key: ERPNEXT_API_KEY
        sync: false
      - key: ERPNEXT_API_SECRET
        sync: false
